server:
  port: 9001
spring:
  application:
    name: zoe-base  #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/base?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true